// Street-Racing-Karriere: drei Kapitel mit je einer Crew, vier Missionen und einem Boss-Rennen.
// Missionen verlangen einen Mindest-Ruf. Ruf gibt es für Missionen, Medaillen in den freien
// Rennen und fürs Abhängen der Polizei.

// Figuren für Dialogkarten, Rivalen und Minimap. car/color/style nur bei Rivalen.
export const CHARS = {
  lola: { name: 'Lola Reyes', role: 'Sunshine Autos', color: '#35f2ff', glyph: 'LR' },
  rico: {
    name: 'Rico „Flamingo“ Valdez',
    short: 'Rico',
    role: 'Boss der Flamingo Kings',
    color: '#ff5fa2',
    glyph: 'RV',
    car: 'corsair',
    paint: '#ff2a6d',
    style: { skill: 1.0, top: 0.9, aggro: 0.7, lane: 0 },
  },
  candy: {
    name: 'Candy Moreau',
    short: 'Candy',
    role: 'Flamingo Kings · Drift',
    color: '#ff9ec4',
    glyph: 'CM',
    car: 'corsair',
    paint: '#16a6c9',
    style: { skill: 0.95, top: 0.88, aggro: 0.5, lane: -1.6, drift: true },
  },
  dash: {
    name: 'Dash Delgado',
    short: 'Dash',
    role: 'Flamingo Kings',
    color: '#ffb3d9',
    glyph: 'DD',
    car: 'spyder',
    paint: '#cfd4d9',
    style: { skill: 0.9, top: 0.87, aggro: 0.3, lane: 1.6 },
  },
  esteban: {
    name: 'Esteban „El Cuervo“ Ortiz',
    short: 'El Cuervo',
    role: 'Boss von Los Cuervos',
    color: '#e0312f',
    glyph: 'EO',
    car: 'fuego',
    paint: '#101010',
    style: { skill: 1.05, top: 0.92, aggro: 0.8, lane: 0 },
  },
  lucia: {
    name: 'Lucía Ferrer',
    short: 'Lucía',
    role: 'Los Cuervos · Drift',
    color: '#ffb400',
    glyph: 'LF',
    car: 'monarch',
    paint: '#b31217',
    style: { skill: 1.0, top: 0.9, aggro: 0.6, lane: -1.6, drift: true },
  },
  paco: {
    name: 'Paco Ramos',
    short: 'Paco',
    role: 'Los Cuervos',
    color: '#ff7a3d',
    glyph: 'PR',
    car: 'monarch',
    paint: '#1b1b1b',
    style: { skill: 0.95, top: 0.88, aggro: 0.4, lane: 1.6 },
  },
  kane: {
    name: 'Victor Kane',
    short: 'Kane',
    role: 'Kopf des Chrome Syndicate',
    color: '#8fb8ff',
    glyph: 'VK',
    car: 'phantom',
    paint: '#f4f4f4',
    style: { skill: 1.1, top: 0.93, aggro: 0.9, lane: 0 },
  },
  mei: {
    name: 'Mei „Ghost“ Tanaka',
    short: 'Mei',
    role: 'Chrome Syndicate · Drift',
    color: '#c9d6ff',
    glyph: 'MT',
    car: 'stiletto',
    paint: '#f4f4f4',
    style: { skill: 1.08, top: 0.92, aggro: 0.7, lane: -1.6, drift: true },
  },
  dex: {
    name: 'Dex Holloway',
    short: 'Dex',
    role: 'Chrome Syndicate',
    color: '#6fa0e8',
    glyph: 'DH',
    car: 'stiletto',
    paint: '#111111',
    style: { skill: 1.0, top: 0.9, aggro: 0.5, lane: 1.6 },
  },
};

// Ränge nach Ruf
export const RANKS = [
  [0, 'Nobody'],
  [150, 'Newcomer'],
  [450, 'Streetracer'],
  [900, 'Lokalmatador'],
  [1400, 'Crew-Schreck'],
  [2000, 'Legende'],
];

export function rankName(rep, champion = false) {
  if (champion) return 'Champion von Vice City';
  let name = RANKS[0][1];
  for (const [min, n] of RANKS) if (rep >= min) name = n;
  return name;
}

// Einführung beim allerersten Start
export const INTRO = [
  { who: 'lola', text: 'Du bist also der Neue, von dem alle reden?\nIch bin Lola Reyes. Mir gehört Sunshine Autos, hier am Ocean Drive.' },
  { who: 'lola', text: 'Nachts zählt in dieser Stadt nur eins: Ruf.\nDen verdienst du dir auf der Straße – bei Rennen, Drifts und gegen die Crews.' },
  { who: 'lola', text: 'Drei Crews teilen sich Vice City: die Flamingo Kings am Strand,\nLos Cuervos in Little Havana und das Chrome Syndicate in Downtown.' },
  {
    who: 'lola',
    text: 'Der weiße Spyder vorn auf dem Platz gehört jetzt dir. Gegen geklaute Kisten fährt hier keiner.\nFahr zur Flamingo Lounge am Ocean Drive (pinke Markierung). Rico wartet nicht gern.',
  },
];

// Kapitel mit Missionsgeber (Treffpunkt der Crew) und Missionen.
// Routen sind Kreuzungen im Straßenraster; die KI plant dazwischen per A*.
export const CHAPTERS = [
  {
    id: 'beach',
    name: 'Vice Beach',
    crew: 'Flamingo Kings',
    boss: 'rico',
    color: '#ff5fa2',
    giver: { name: 'Flamingo Lounge', x: 576.5, z: 290 },
    missions: [
      {
        id: 'c1-sprint',
        name: 'Erste Runde',
        type: 'race',
        desc: 'Sprint gegen Dash: Ocean Drive hoch, über Collins Avenue ans Nordende.',
        req: 0,
        reward: 600,
        rep: 60,
        rivals: ['dash'],
        route: [[580, 400], [580, -200], [470, -200], [470, -600]],
        intro: [
          { who: 'rico', text: 'Lola schickt mir einen Frischling? Na gut.\nDash, zeig ihm, wie schnell Vice Beach ist.' },
          { who: 'dash', text: 'Ocean Drive hoch, rüber auf die Collins, bis ganz nach Norden.\nWer zuerst oben ist, hat recht.' },
        ],
        outro: [
          { who: 'dash', text: 'Okay … das war knapp. Glückwunsch.' },
          { who: 'rico', text: 'Nicht schlecht, Frischling. Candy will dich driften sehen.\nKomm wieder in die Lounge.' },
        ],
      },
      {
        id: 'c1-drift',
        name: 'Pink Drift',
        type: 'drift',
        desc: 'Schlag Candys Drift-Punktzahl innerhalb von 60 Sekunden.',
        req: 40,
        reward: 700,
        rep: 60,
        rival: 'candy',
        target: 6000,
        limit: 60,
        route: [[470, 400], [470, 200]],
        intro: [{ who: 'candy', text: 'Schnell fahren kann jeder.\nIch will sehen, ob du quer genauso gut bist. 6.000 Punkte, eine Minute.' }],
        outro: [{ who: 'candy', text: 'Hm. Saubere Linie, gute Winkel.\nIch sag Rico, dass du mehr drauf hast als einen schnellen Fuß.' }],
      },
      {
        id: 'c1-courier',
        name: 'Kurierfahrt',
        type: 'delivery',
        desc: 'Bring Ricos Fuego GT ohne Kratzer zur Lackiererei in Downtown.',
        req: 100,
        reward: 900,
        rep: 80,
        giverWho: 'rico',
        car: 'fuego',
        paint: '#ffcc00',
        route: [[360, 200], [360, 0]],
        dest: { x: -53, z: 100, name: 'Lackiererei Downtown' },
        limit: 55,
        maxDamage: 0.3,
        intro: [
          { who: 'rico', text: 'Mein Fuego muss zur Lackiererei in Downtown. Heute noch.\nÜber den Causeway, Zeit hast du 55 Sekunden.' },
          { who: 'rico', text: 'Und hör zu: Kommt er mit Beulen an, fährst du nie wieder für uns.' },
        ],
        outro: [{ who: 'rico', text: 'Pünktlich und ohne Kratzer. Man kann sich auf dich verlassen.\nDein eigener Wagen steht schon für dich bereit.' }],
      },
      {
        id: 'c1-duel',
        name: 'Drei gegen einen',
        type: 'race',
        desc: 'Dash und Candy gegen dich: über den Vice Causeway nach Downtown.',
        req: 180,
        reward: 1000,
        rep: 90,
        rivals: ['dash', 'candy'],
        route: [[580, 200], [580, 0], [360, 0], [100, 0], [100, 200], [-50, 200]],
        intro: [
          { who: 'candy', text: 'Rico will wissen, ob du auch gegen zwei bestehst.' },
          { who: 'dash', text: 'Über den Vice Causeway nach Downtown. Mit Nitro fliegt man da richtig.\nVersuch einfach, uns nicht aus den Augen zu verlieren.' },
        ],
        outro: [{ who: 'rico', text: 'Zwei meiner Leute geschlagen. Jetzt reden wir beide.\nWenn du genug Ruf hast, fahren wir ums Revier.' }],
      },
      {
        id: 'c1-boss',
        name: 'Flamingo Kings',
        type: 'race',
        boss: true,
        desc: 'Boss-Rennen: zwei Runden um Vice Beach gegen Rico und seine Crew.',
        req: 300,
        reward: 3000,
        rep: 200,
        rivals: ['rico', 'candy', 'dash'],
        route: [[580, -200], [580, 200], [360, 200], [360, -200]],
        laps: 2,
        intro: [
          { who: 'rico', text: 'Vice Beach gehört den Flamingo Kings, seit es hier Neon gibt.\nZwei Runden um die Insel. Gewinnst du, hört der Strand auf dich.' },
        ],
        outro: [
          { who: 'rico', text: 'Respekt. Vice Beach hat einen neuen Namen auf der Liste.' },
          { who: 'lola', text: 'Das hat sich rumgesprochen. Los Cuervos in Little Havana wollen dich kennenlernen.\nTreffpunkt ist das Café Cuervo an der Flamingo Street.' },
        ],
      },
    ],
  },
  {
    id: 'havana',
    name: 'Little Havana',
    crew: 'Los Cuervos',
    boss: 'esteban',
    color: '#e0312f',
    giver: { name: 'Café Cuervo', x: -347, z: -100 },
    missions: [
      {
        id: 'c2-tail',
        name: 'Der Schatten',
        type: 'tail',
        desc: 'Folge Paco unauffällig zu seinem Versteck. Nicht zu nah, nicht verlieren.',
        req: 450,
        reward: 1200,
        rep: 100,
        rival: 'paco',
        cruise: 16,
        route: [[-350, -400], [-350, 0], [-500, 0], [-500, 400], [-350, 400], [-350, 600]],
        intro: [
          { who: 'esteban', text: 'Der Strandjunge. Bevor du bei uns fährst, will ich wissen, ob du Geduld hast.' },
          { who: 'esteban', text: 'Paco bringt heute etwas in unsere Garage. Folge ihm, ohne dass er dich bemerkt.\nBleib auf Abstand – aber verlier ihn nicht.' },
        ],
        outro: [{ who: 'paco', text: 'Du warst die ganze Zeit hinter mir? Ernsthaft?\nOkay, El Cuervo wird das gefallen.' }],
      },
      {
        id: 'c2-heat',
        name: 'Heißes Pflaster',
        type: 'race',
        desc: 'Rennen gegen Lucía quer durch Little Havana – mit der Polizei im Nacken.',
        req: 540,
        reward: 1500,
        rep: 110,
        rivals: ['lucia'],
        police: 2,
        route: [[-200, -600], [-200, -200], [-350, -200], [-350, 200], [-500, 200], [-500, 600]],
        intro: [
          { who: 'lucia', text: 'Heute Nacht patrouillieren die Cops in ganz Havana.\nPerfekt. Wer vorne bleibt und nicht erwischt wird, gewinnt.' },
        ],
        outro: [{ who: 'lucia', text: 'Mit zwei Streifenwagen am Heck und trotzdem vorn. Nicht übel.\nHäng sie noch ab, bevor du hier wieder aufkreuzt.' }],
      },
      {
        id: 'c2-drift',
        name: 'Havana Nights',
        type: 'drift',
        desc: 'Drift-Battle gegen Lucía: 9.000 Punkte in 60 Sekunden.',
        req: 650,
        reward: 1500,
        rep: 110,
        rival: 'lucia',
        target: 9000,
        limit: 60,
        route: [[-500, -400], [-500, -200]],
        intro: [{ who: 'lucia', text: 'Rennen gewinnen ist eine Sache. Stil ist eine andere.\n9.000 Punkte, eine Minute. Zeig mir, dass du tanzen kannst.' }],
        outro: [{ who: 'lucia', text: 'Okay, du kannst tanzen.\nEsteban hat noch einen Auftrag für dich.' }],
      },
      {
        id: 'c2-parts',
        name: 'Ersatzteile',
        type: 'delivery',
        desc: 'Fahr die schwer beladene Admiral-Limousine aus Downtown zur Crew-Garage.',
        req: 760,
        reward: 1800,
        rep: 120,
        giverWho: 'esteban',
        car: 'sedan',
        paint: '#6d6d6d',
        route: [[-50, -400], [-50, -200]],
        dest: { x: -347, z: 470, name: 'Garage der Cuervos' },
        limit: 75,
        maxDamage: 0.35,
        intro: [
          { who: 'esteban', text: 'Im Kofferraum der Admiral liegen Motorteile für meinen Fuego.\nTeuer und empfindlich. 75 Sekunden bis zu unserer Garage.' },
        ],
        outro: [{ who: 'esteban', text: 'Alles heil angekommen. Du bist bereit.\nWenn dein Ruf stimmt, fahren wir beide – über den Highway.' }],
      },
      {
        id: 'c2-boss',
        name: 'El Cuervo',
        type: 'race',
        boss: true,
        desc: 'Boss-Rennen über den Vice Highway gegen Esteban, Lucía und Paco.',
        req: 950,
        reward: 5000,
        rep: 250,
        rivals: ['esteban', 'lucia', 'paco'],
        route: [[-500, -600], [-650, -600], [-650, 600], [-500, 600], [-500, 200], [-200, 200]],
        intro: [
          { who: 'esteban', text: 'Mein Vater ist hier Rennen gefahren, als der Highway noch Schotter war.\nEinmal runter bis zum Südende, dann zurück nach Havana. Keine Ausreden.' },
        ],
        outro: [
          { who: 'esteban', text: 'Du fährst mit dem Herz, nicht nur mit dem Fuß. Havana respektiert das.' },
          { who: 'lola', text: 'Jetzt fehlt nur noch einer: Victor Kane und sein Chrome Syndicate.\nSie treffen sich am Kane Tower in Downtown. Sei vorsichtig, Kane spielt nicht fair.' },
        ],
      },
    ],
  },
  {
    id: 'downtown',
    name: 'Downtown',
    crew: 'Chrome Syndicate',
    boss: 'kane',
    color: '#8fb8ff',
    giver: { name: 'Kane Tower', x: -53, z: -300 },
    missions: [
      {
        id: 'c3-loop',
        name: 'Glas und Stahl',
        type: 'race',
        desc: 'Zwei Runden zwischen den Glastürmen gegen Dex und Mei.',
        req: 1150,
        reward: 2200,
        rep: 130,
        rivals: ['dex', 'mei'],
        route: [[100, -200], [-50, -200], [-50, 200], [100, 200]],
        laps: 2,
        intro: [
          { who: 'kane', text: 'Der Champion vom Strand und aus Havana. Wie niedlich.\nIn Downtown fährt man zwischen Glas und Stahl. Dex, Mei – zeigt es ihm.' },
        ],
        outro: [{ who: 'dex', text: 'Das war kein Glück. Kane wird nervös werden.' }],
      },
      {
        id: 'c3-ghost',
        name: 'Ghost',
        type: 'tail',
        desc: 'Folge Mei über den Starfish Causeway, ohne entdeckt zu werden.',
        req: 1300,
        reward: 2400,
        rep: 130,
        rival: 'mei',
        cruise: 20,
        route: [[-200, -200], [-200, -400], [100, -400], [360, -400], [360, -600], [580, -600]],
        intro: [
          { who: 'lola', text: 'Kane plant etwas. Mei fährt heute Nacht zu seinem geheimen Treffpunkt.\nFolge ihr. Sie heißt nicht umsonst „Ghost“ – sie ist schnell und merkt alles.' },
        ],
        outro: [{ who: 'lola', text: 'Eine Halle am Nordende von Vice Beach. Kane lässt dort Prototypen umbauen.\nDas erklärt einiges.' }],
      },
      {
        id: 'c3-hot',
        name: 'Heiße Ware',
        type: 'delivery',
        desc: 'Bring den Stiletto-Prototyp mit Polizei im Nacken zu Lola nach Vice Beach.',
        req: 1450,
        reward: 2800,
        rep: 140,
        giverWho: 'lola',
        car: 'stiletto',
        paint: '#d10b0b',
        police: 2,
        route: [[-200, 200], [-50, 200]],
        dest: { x: 473, z: 500, name: 'Lolas Hinterhof' },
        limit: 85,
        maxDamage: 0.4,
        intro: [
          { who: 'lola', text: 'Kane hat den Prototyp einem Händler gestohlen, der mir noch was schuldet.\nHol ihn zurück. Die Polizei sucht den Wagen – rechne mit Streifen.' },
          { who: 'lola', text: 'Bring ihn in meinen Hinterhof auf Vice Beach. 85 Sekunden, und bitte in einem Stück.' },
        ],
        outro: [{ who: 'lola', text: 'Der Händler bekommt seinen Wagen zurück, und Kane ist sauer.\nGenau so, wie ich es mag.' }],
      },
      {
        id: 'c3-drift',
        name: 'Chrome Drift',
        type: 'drift',
        desc: 'Mei fordert dich heraus: 12.000 Drift-Punkte in 60 Sekunden.',
        req: 1600,
        reward: 3000,
        rep: 150,
        rival: 'mei',
        target: 12000,
        limit: 60,
        route: [[-200, -400], [-200, -200]],
        intro: [{ who: 'mei', text: 'Du hast mich verfolgt. Clever.\nJetzt fahren wir fair: 12.000 Punkte. Wenn du das schaffst, stehe ich an der Startlinie hinter dir.' }],
        outro: [{ who: 'mei', text: 'Gut gefahren. Kane wird dich fordern.\nEr fährt den Phantom X. Unterschätz ihn nicht.' }],
      },
      {
        id: 'c3-final',
        name: 'Victor Kane',
        type: 'race',
        boss: true,
        desc: 'Finale: vom Highway quer durch die Stadt, über den Vice Causeway bis ans Nordende von Vice Beach.',
        req: 1800,
        reward: 10000,
        rep: 400,
        rivals: ['kane', 'mei', 'dex'],
        police: 1,
        route: [[-650, 600], [-650, 0], [100, 0], [360, 0], [580, 0], [580, -600]],
        intro: [
          { who: 'kane', text: 'Einmal quer durch meine Stadt. Vom Highway bis an den Strand.\nDu gegen das Syndicate. Und die Polizei weiß schon Bescheid – das habe ich arrangiert.' },
          { who: 'lola', text: 'Das ist es. Fahr einfach dein Rennen. Die ganze Stadt schaut zu.' },
        ],
        outro: [
          { who: 'kane', text: '… Gut. Die Stadt gehört dir. Vorerst.' },
          { who: 'lola', text: 'Vom Nobody zum Champion von Vice City.\nIch habe es immer gewusst. Und jetzt – fahr einfach. Die Nacht ist noch jung.' },
        ],
      },
    ],
  },
];

export const ALL_MISSIONS = CHAPTERS.flatMap((ch, ci) => ch.missions.map((m, mi) => ({ ...m, ch, ci, mi })));
